apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: locust-master
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - env:
        - name: LOCUST_MODE
          value: master
        - name: TARGET_HOST
          value: https://coview-automation.texel.live
        image: gcr.io/charged-mind-247422/loadtest:latest
        name: locust-master
        ports:
        - containerPort: 8089
          name: loc-master-web
          protocol: TCP
        - containerPort: 5557
          name: loc-master-p1
          protocol: TCP
        - containerPort: 5558
          name: loc-master-p2
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 1000m
        volumeMounts:
        - mountPath: /locust_statistic
          name: locuststatistic
      volumes:
      - name: locuststatistic
        persistentVolumeClaim:
          claimName: load-statistics
